### ISSUE TITLE
是否可以考虑再增加一部分案例或者提供更详细的文档？

### ISSUE THREAD

**Issue by lystrosaurus** [CyrilFeng/Q-calculator#11]
您好：
      目前看完介绍跑完demo有一些疑惑的点：
   
1. 关于互斥组，目前是支持2个，会转换成共享组，

类似如果用户包含的资产里面有A,B,C,D：（A,B）互斥 ，（C,D）互斥，(B,D)互斥，(A,C)(B,C)(A,D) 共享，不太理解按现有结构要如何配置才能支持

2. 关于自定义的规则部分，目前demo里面有满减和折扣的示例，但是，不是很清晰

类似：如果券作用是在单商品上的，只能被用一次（多个数量只能用一个），代码里面有个records描述可以记录商品的优惠，自定义逻辑。
方便的话可以给个示例，还有有些券被商品使用了，需要标记被使用，不能参与计算了，这种。

```java
final DiscountConfig discountConfig = new DiscountConfig();
        discountConfig.setCalculateGroup(10);
        discountConfig.setGoodsType(1);
        discountConfig.setItemIds(ImmutableList.of(1001L));
        discountConfig.setItemIdType(0);
```

```json
{
    "6667": [
        {
            "beforeCalcPrice": 10000,
            "afterCalcPrice": 8000,
            "stageType": "manjian",
            "index": 0,
            "extra": null
        },
        {
            "beforeCalcPrice": 8000,
            "afterCalcPrice": 6667,
            "stageType": "zhekou",
            "index": 1,
            "extra": null
        }
    ]
}
```

如果可能的话，可以把文档更详细一些，或者一个相对复杂的使用示例，会更方便理解。

最后，之前没有接触过电商项目，所以比较小白
在找到这个仓库之前：
看了 [严选促销中心价格计算体系的建设之路](https://www.cnblogs.com/purple5252/p/15166436.html), [vivo商城计价中心](https://zhuanlan.zhihu.com/p/402570352) 看着场景都很符合，但是自己一个人实现就头大了，都很困难。

全网或许只有你们一个开源这种算法的，非常感谢。

**Comment by CyrilFeng** [comment]
一切思路都是转化为共享组，其余默认就是互斥的 所以你只需要配置（A,C)(B,C)(A,D)  3个共享组

```
[
    {
        "relation": "share",
        "items":
        [
            {
                "type": "A",
                "id": "11"
            }
            ,
            {
                "type": "C",
                "id": "13"
            } 
        ]
    }]

[
    {
        "relation": "share",
        "items":
        [
            {
                "type": "B",
                "id": "11"
            }
            ,
            {
                "type": "C",
                "id": "13"
            } 
        ]
    }]

[
    {
        "relation": "share",
        "items":
        [
            {
                "type": "A",
                "id": "11"
            }
            ,
            {
                "type": "D",
                "id": "13"
            } 
        ]
    }]

```

**Comment by CyrilFeng** [comment]
[有些券被商品使用了，需要标记被使用，不能参与计算了。](url)
参考cn.qmai.discount.core.permutation.Permutation类的逻辑，这个算法会排列所有的情况，并在内部通过一个CalcStage自动记录状态，你可以参考cn.qmai.discount.core.discount.impl.AbstractCalculator#calcWarp

**Comment by CyrilFeng** [comment]
records的使用很简单，它只是个容器，你只需要把用过权益的商品丢进去即可。它是全局的，意味着你可以再下一个计算器中判断你的逻辑。

**Comment by CyrilFeng** [comment]
demo中只有2个权益，虽然你改了discount 但是计算结果满减放前面才是最优的。你可以修改demo满减的内容试试。
这个框架的核心部分在cn.qmai.discount.core.permutation.Permutation和cn.qmai.discount.core.discount.impl.AbstractCalculator，你可以只读懂这2个类的思想自己实现你的算法。

**Comment by lystrosaurus** [comment]
收到，感谢回复，我试试
